### PR TITLE
Add gem test

### PR DESCRIPTION
**Pull request by daipom**
* #5 

Following this, I added CI for Gem.

Currently, the test fails because of the following issue.

* #6

### CODE REVIEW

**Comment by daipom** [comment]
I will rebase this. Then All tests will succeed.

**Comment by daipom** [comment]
Now all tests have succeeded.

Only the new gem test uses the latest Fluentd, and other tests use v1.12 for now.

When the following fix of Fluentd is merged, other tests also start to use the latest Fluentd.

* https://github.com/fluent/fluentd/pull/4061

Or perhaps we can adjust gemfile or gemspec of this repository.

**Comment by kenhys** [comment]
> When the following fix of Fluentd is merged, other tests also start to use the latest Fluentd.

It is enough to just wait PR merged, IMHO.

But it is good practice to test with latest version, so how about using latest Fluentd in gem job?
I mean inserting `gem install fluentd` to gem job.

**Review by kenhys — APPROVED** [review]
LGTM.

**Comment by daipom** [comment]
Thanks for your review!

**Pull request merged**
