### PR TITLE
CI: Support Fluentd after v1.13.3

### LINKED ISSUE #6: CI: Support Fluentd after v1.13.3
The CI is updated in #5, but Bundler is still choosing Fluentd v1.12, not the latest Fluentd v1.15.3.

https://github.com/fluent-plugins-nursery/fluent-plugin-utmpx/actions/runs/4201345210/jobs/7288262037#step:3:69

It is the same in my local with Ruby 3.2.0.

Some tests fail on Fluentd v1.15.3.
(`$ bundle exec rake test` is successful, but just `$ rake test` is not)

```
.......E
==================================================================================================================================================================================================================================================================================
Error: test_pos_file(UtmpxInputTest::pos_file use cases): ArgumentError: wrong number of arguments (given 3, expected 2)
/home/daipom/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_tail/position_file.rb:31:in `initialize'
/home/daipom/work/fluentd/plugins/embedded-in-td-agent/fluent-plugin-utmpx/test/plugin/test_in_utmpx.rb:93:in `new'
/home/daipom/work/fluentd/plugins/embedded-in-td-agent/fluent-plugin-utmpx/test/plugin/test_in_utmpx.rb:93:in `block in test_pos_file'
     90:           @pf = Fluent::Plugin::TailInput::PositionFile.new(file, logger: nil)
     91:           @pe = @pf[wtmp_path]
     92:         else
  => 93:           @pf = Fluent::Plugin::TailInput::PositionFile.new(file, false, {wtmp_path => target_info}, logger: nil)
     94:           @pe = @pf[target_info]
     95:         end
     96:         @pe.update_pos(@tail_position)
/home/daipom/work/fluentd/plugins/embedded-in-td-agent/fluent-plugin-utmpx/test/plugin/test_in_utmpx.rb:87:in `open'
/home/daipom/work/fluentd/plugins/embedded-in-td-agent/fluent-plugin-utmpx/test/plugin/test_in_utmpx.rb:87:in `test_pos_file'
==================================================================================================================================================================================================================================================================================
E
==================================================================================================================================================================================================================================================================================
Error: test_truncated(UtmpxInputTest::pos_file use cases): ArgumentError: wrong number of arguments (given 3, expected 2)
/home/daipom/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/fluentd-1.15.3/lib/fluent/plugin/in_tail/position_file.rb:31:in `initialize'
/home/daipom/work/fluentd/plugins/embedded-in-td-agent/fluent-plugin-utmpx/test/plugin/test_in_utmpx.rb:117:in `new'
/home/daipom/work/fluentd/plugins/embedded-in-td-agent/fluent-plugin-utmpx/test/plugin/test_in_utmpx.rb:117:in `block in test_truncated'
     114:           @pf = Fluent::Plugin::TailInput::PositionFile.new(file, logger: nil)
     115:           @pe = @pf[wtmp_path]
     116:         else
  => 117:           @pf = Fluent::Plugin::TailInput::PositionFile.new(file, false, {wtmp_path => target_info}, logger: nil)
     118:           @pe = @pf[target_info]
     119:         end
     120:         @pe.update_pos(@tail_position)
/home/daipom/work/fluentd/plugins/embedded-in-td-agent/fluent-plugin-utmpx/test/plugin/test_in_utmpx.rb:111:in `open'
/home/daipom/work/fluentd/plugins/embedded-in-td-agent/fluent-plugin-utmpx/test/plugin/test_in_utmpx.rb:111:in `test_truncated'
==================================================================================================================================================================================================================================================================================

Finished in 31.615735198 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
9 tests, 10 assertions, 0 failures, 2 errors, 0 pendings, 0 omissions, 0 notifications
77.7778% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
0.28 tests/s, 0.32 assertions/s
rake aborted!
```

### PR DESCRIPTION
**Pull request by daipom**
* Fix #6

I confirmed this makes the following CI successful.

* #7

### CODE REVIEW

**Review by kenhys — APPROVED** [review]
LGTM.

**Comment by daipom** [comment]
Thanks for your review!

**Comment by kenhys** [comment]
NOTE:  fluentd v1.14.0 or later must be required.

**Comment by daipom** [comment]
> NOTE: fluentd v1.14.0 or later must be required.

Oh, could this cause the tests not to work on v1.13.3 or so on?

**Comment by kenhys** [comment]
> Oh, could this cause the tests not to work on v1.13.3 or so on?

Oops, I've misinterpreted the introduced changes. 
(PositionFile load interface is not changed, so no need to require newer version.)

**Comment by daipom** [comment]
> > Oh, could this cause the tests not to work on v1.13.3 or so on?
> 
> Oops, I've misinterpreted the introduced changes. (PositionFile load interface is not changed, so no need to require newer version.)

Yes! I think so too! The codes in `lib/` use `PositionFile.load` from before.
I have confirmed the current tests succeed on Fluentd v1.13,3!

**Pull request merged**
